name: zef_ddd_core
description: A comprehensive Dart library designed to facilitate the implementation of Domain-Driven Design (DDD) principles in your applications
version: 0.0.1
homepage: https://www.zooper.dev
repository: https://github.com/zooper-lib/ZEF_DDD_Core
topics:
  - ddd
  - domain-driven-design
  - clean-architecture
  - domain-events
  - eventing
funding:
  - https://buymeacoffee.com/zooperlib

environment:
  sdk: ^3.3.0

dependencies:

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
